# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080

  web:
    image: woraprat/node-web-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgresdb